### ISSUE TITLE
Parameterize the network driver for dataplane

### ISSUE THREAD

**Issue by ibaldin** [RENCI-NRIG/neuca-agent#2]
Currently the driver is hardcoded into the coded (virtio-net). We should parameterize it so it can be controlled by Puppet. One driving usecase is XDP - e1000 driver supports it, virtio-net does not. On some ExoGENI racks it may be desirable to use e1000 driver to support XDP in the dataplane without redeploying a custom version of neuca-agent.

**Comment by vjorlikowski** [comment]
Code has been completed with:
https://github.com/RENCI-NRIG/neuca-agent/commit/6a64382caf664e0d74b282a5fec5f13b422aba39

Awaiting deployment to all racks by: @mcevik0 

Code, as written, allows for having a "default" interface type for racks, with individual interfaces on VMs possibly being specified as having a different type in the database (presuming ORCA provides this information).

**Comment by vjorlikowski** [comment]
@mcevik0 Feel free to close this ticket, once the code has been deployed to all racks.

**Comment by mcevik0** [comment]
openstack-quantum-neuca-0.2-exogeni5.el6.noarch is deployed to all racks. 
Puppet configuration is updated for dataplane_interface_type on the head-nodes.
WVN, WSU, UAF racks are configured with "e1000" driver.
